version: "3.8"

services:
  do_an_tot_nghiep:
    build: .
    ports:
      - "8082:8082"
    volumes:
      - D:/res_free/user_data:/app/user_data
      - D:/res_free/login_history:/app/login_history
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 8082
